# Generated by Django 5.0.3 on 2024-03-29 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofelix_app', '0002_alter_series_image_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='name',
            field=models.CharField(help_text='Nombre de la carpeta', max_length=100),
        ),
        migrations.AlterField(
            model_name='folders',
            name='userID',
            field=models.ForeignKey(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, to='sofelix_app.users'),
        ),
        migrations.AlterField(
            model_name='series',
            name='chapter',
            field=models.IntegerField(help_text='Capítulo', max_length=10, verbose_name='Capítulo'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.URLField(blank=True, help_text='Imagen', null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='link',
            field=models.URLField(blank=True, help_text='Link', null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(help_text='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='season',
            field=models.IntegerField(help_text='Temporada', max_length=10, verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='series',
            name='userID',
            field=models.ForeignKey(help_text='Usuario', on_delete=django.db.models.deletion.CASCADE, to='sofelix_app.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(help_text='Nombre', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(help_text='Password', max_length=100),
        ),
        migrations.CreateModel(
            name='Series_Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofelix_app.folders', verbose_name='Carpeta')),
                ('serieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sofelix_app.series', verbose_name='Serie')),
            ],
        ),
    ]
